### ISSUE TITLE
When i use python 3 i got this error.

### ISSUE THREAD

**Issue by coolzhengtao** [husio/python-sqlite3-backup#11]
```
======================================================================
ERROR: test_load_from_file_into_memory (__main__.SqliteBackpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 124, in test_load_from_file_into_memory
    sqlitebck.copy(source_db, db_dest)
sqlite3.DataError: Database in transaction

----------------------------------------------------------------------
```

could this lib run at python 3? Thanks a lot.

**Comment by husio** [comment]
I just plugged [travis builds](https://travis-ci.org/husio/python-sqlite3-backup/builds/311709304?utm_source=github_status&utm_medium=notification) and they build green. Can you reproduce the issue every time? What version of python and sqlite are you using?

**Comment by coolzhengtao** [comment]
My environment is Python 3.6.3, macOS 10.12.6, sqlite 3.20.1
Steps is:
1. I created python virtualenv use python 3.6.3
2. I ran this command:
```sh
source venv/bin/activate
python setup.py build
```
the result is:
```sh
running build
running build_ext
building 'sqlitebck' extension
creating build
creating build/temp.macosx-10.12-x86_64-3.6
creating build/temp.macosx-10.12-x86_64-3.6/src
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/sqlitebck.c -o build/temp.macosx-10.12-x86_64-3.6/src/sqlitebck.o
creating build/lib.macosx-10.12-x86_64-3.6
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.12-x86_64-3.6/src/sqlitebck.o -lsqlite3 -o build/lib.macosx-10.12-x86_64-3.6/sqlitebck.cpython-36m-darwin.so
```
3. next i ran this:
```sh
python setup.py install
```
result is:
```sh
running install
running build
running build_ext
running install_lib
copying build/lib.macosx-10.12-x86_64-3.6/sqlitebck.cpython-36m-darwin.so -> /Users/zhengtao/test-project/python-sqlite3-backup/venv/lib/python3.6/site-packages
running install_egg_info
Writing /Users/zhengtao/test-project/python-sqlite3-backup/venv/lib/python3.6/site-packages/sqlitebck-1.3-py3.6.egg-info
```
4. i ran test use:
```sh
python tests.py
```
and i got this error
```sh
/Users/zhengtao/test-project/python-sqlite3-backup/build/lib.macosx-10.12-x86_64-3.6
EEE...E
======================================================================
ERROR: test_inerited_destination (__main__.CopyInheritedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 59, in test_inerited_destination
    sqlitebck.copy(self.native, self.inherited)
sqlite3.DataError: Database in transaction

======================================================================
ERROR: test_inerited_source (__main__.CopyInheritedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 52, in test_inerited_source
    sqlitebck.copy(self.inherited, self.native)
sqlite3.DataError: Database in transaction

======================================================================
ERROR: test_copy_from_memory_database (__main__.SqliteBackpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 102, in test_copy_from_memory_database
    sqlitebck.copy(source=source_db, dest=db_dest)
sqlite3.DataError: Database in transaction

======================================================================
ERROR: test_load_from_file_into_memory (__main__.SqliteBackpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 124, in test_load_from_file_into_memory
    sqlitebck.copy(source_db, db_dest)
sqlite3.DataError: Database in transaction

----------------------------------------------------------------------
Ran 7 tests in 0.010s

FAILED (errors=4)
```
Thanks a lot. I wish you can fix it. Now i change to python2.7 and everything is ok.

**Comment by coolzhengtao** [comment]
Sorry, It is still wrong.But i got this output with debug info:
```sh
/Users/zhengtao/test-project/python-sqlite3-backup/build/lib.macosx-10.12-x86_64-3.6

SQLite module version: 2.6.0
Python version: 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

    EEE...E
======================================================================
ERROR: test_inerited_destination (__main__.CopyInheritedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 61, in test_inerited_destination
    sqlitebck.copy(self.native, self.inherited)
sqlite3.DataError: Database in transaction

======================================================================
ERROR: test_inerited_source (__main__.CopyInheritedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 54, in test_inerited_source
    sqlitebck.copy(self.inherited, self.native)
sqlite3.DataError: Database in transaction

======================================================================
ERROR: test_copy_from_memory_database (__main__.SqliteBackpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 102, in test_copy_from_memory_database
    sqlitebck.copy(source=source_db, dest=db_dest)
sqlite3.DataError: Database in transaction

======================================================================
ERROR: test_load_from_file_into_memory (__main__.SqliteBackpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 126, in test_load_from_file_into_memory
    sqlitebck.copy(source_db, db_dest)
sqlite3.DataError: Database in transaction

----------------------------------------------------------------------
Ran 7 tests in 0.008s

FAILED (errors=4)
```
thanks a lot.

**Comment by husio** [comment]
I cannot reproduce this locally running the same versions on linux.
I don't know what could be the problem, so I have tol keep guessing.

 - do you have custom sqlite settings that oculd be loaded during the test? Maybe an rc file?
- can you check if version https://github.com/husio/python-sqlite3-backup/commit/fbd74ca40314eb0bbd414796fa16ee00f154744b is working for you?

**Comment by grantHarris** [comment]
I just ran into this same issue with Python3 on OSX
